In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
ev_df = pd.read_csv(r'C:\Users\srired\OneDrive - DNV\Python Learning Folder\Electric_Vehicle_Population_Data.csv')
print(ev_df.head(5))
print(ev_df.info())

   VIN (1-10)     County       City State  Postal Code  Model Year   Make  \
0  5YJYGDEE1L       King    Seattle    WA      98122.0        2020  TESLA
1  7SAYGDEE9P  Snohomish    Bothell    WA      98021.0        2023  TESLA
2  5YJSA1E4XK       King    Seattle    WA      98109.0        2019  TESLA
3  5YJSA1E27G       King   Issaquah    WA      98027.0        2016  TESLA
4  5YJYGDEE5M     Kitsap  Suquamish    WA      98392.0        2021  TESLA

     Model           Electric Vehicle Type  \
0  MODEL Y  Battery Electric Vehicle (BEV)
1  MODEL Y  Battery Electric Vehicle (BEV)
2  MODEL S  Battery Electric Vehicle (BEV)
3  MODEL S  Battery Electric Vehicle (BEV)
4  MODEL Y  Battery Electric Vehicle (BEV)

   Clean Alternative Fuel Vehicle (CAFV) Eligibility  Electric Range  \
0            Clean Alternative Fuel Vehicle Eligible             291
1  Eligibility unknown as battery range has not b...               0
2            Clean Alternative Fuel Vehicle Eligible             270
3            Clean Alternative Fuel Vehicle Eligible             210
4  Eligibility unknown as battery range has not b...               0

   Base MSRP  Legislative District  DOL Vehicle ID  \
0          0                  37.0       125701579
1          0                   1.0       244285107
2          0                  36.0       156773144
3          0                   5.0       165103011
4          0                  23.0       205138552

                Vehicle Location  \
0   POINT (-122.30839 47.610365)
1  POINT (-122.179458 47.802589)
2   POINT (-122.34848 47.632405)
3   POINT (-122.03646 47.534065)
4   POINT (-122.55717 47.733415)

                                Electric Utility  2020 Census Tract
0   CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)       5.303301e+10
1                         PUGET SOUND ENERGY INC       5.306105e+10
2   CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)       5.303301e+10
3  PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)       5.303303e+10
4                         PUGET SOUND ENERGY INC       5.303594e+10
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177866 entries, 0 to 177865
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         177866 non-null  object
 1   County                                             177861 non-null  object
 2   City                                               177861 non-null  object
 3   State                                              177866 non-null  object
 4   Postal Code                                        177861 non-null  float64
 5   Model Year                                         177866 non-null  int64
 6   Make                                               177866 non-null  object
 7   Model                                              177866 non-null  object
 8   Electric Vehicle Type                              177866 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  177866 non-null  object
 10  Electric Range                                     177866 non-null  int64
 11  Base MSRP                                          177866 non-null  int64
 12  Legislative District                               177477 non-null  float64
 13  DOL Vehicle ID                                     177866 non-null  int64
 14  Vehicle Location                                   177857 non-null  object
 15  Electric Utility                                   177861 non-null  object
 16  2020 Census Tract                                  177861 non-null  float64
dtypes: float64(3), int64(4), object(10)
memory usage: 23.1+ MB
None

In [17]:
#Summary statistics of all columns
ev_df.describe(include='all')

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
count,177866,177861,177861,177866,177861.000000,177866.000000,177866,177866,177866,177866,177866.000000,177866.000000,177477.000000,1.778660e+05,177857,177861,1.778610e+05
unique,10830,196,723,46,NaN,NaN,40,139,2,3,NaN,NaN,NaN,NaN,861,76,NaN
top,7SAYGDEE6P,King,Seattle,WA,NaN,NaN,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,NaN,NaN,NaN,NaN,POINT (-122.12302 47.67668),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),NaN
freq,1239,92740,29447,177477,NaN,NaN,79659,35989,139210,91950,NaN,NaN,NaN,NaN,4574,65990,NaN
mean,NaN,NaN,NaN,NaN,98172.453506,2020.515512,NaN,NaN,NaN,NaN,58.842162,1073.109363,29.127481,2.202313e+08,NaN,NaN,5.297672e+10
std,NaN,NaN,NaN,NaN,2442.450668,2.989384,NaN,NaN,NaN,NaN,91.981298,8358.624956,14.892169,7.584987e+07,NaN,NaN,1.578047e+09
min,NaN,NaN,NaN,NaN,1545.000000,1997.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,4.385000e+03,NaN,NaN,1.001020e+09
25%,NaN,NaN,NaN,NaN,98052.000000,2019.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,18.000000,1.814743e+08,NaN,NaN,5.303301e+10
50%,NaN,NaN,NaN,NaN,98122.000000,2022.000000,NaN,NaN,NaN,NaN,0.000000,0.000000,33.000000,2.282522e+08,NaN,NaN,5.303303e+10
75%,NaN,NaN,NaN,NaN,98370.000000,2023.000000,NaN,NaN,NaN,NaN,75.000000,0.000000,42.000000,2.548445e+08,NaN,NaN,5.305307e+10
max,NaN,NaN,NaN,NaN,99577.000000,2024.000000,NaN,NaN,NaN,NaN,337.000000,845000.000000,49.000000,4.792548e+08,NaN,NaN,5.603300e+10

In [19]:
#Missing data count
ev_df.isnull().sum()

VIN (1-10)                                             0
County                                                 5
City                                                   5
State                                                  0
Postal Code                                            5
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         0
Base MSRP                                              0
Legislative District                                 389
DOL Vehicle ID                                         0
Vehicle Location                                       9
Electric Utility                                       5
2020 Census Tract                                      5
dtype: int64

In [24]:
#Rows with null values
ev_df[ev_df.isnull().any(axis=1)]

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
57115,1G1FZ6S00K,Washoe,Reno,NV,89521.0,2019,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238,0,NaN,231094930,POINT (-119.74505 39.436555),NON WASHINGTON STATE ELECTRIC UTILITY,3.203100e+10
75427,5YJSA1E54P,District of Columbia,Washington,DC,20003.0,2023,TESLA,MODEL S,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,NaN,238713044,POINT (-76.985835 38.88411),NON WASHINGTON STATE ELECTRIC UTILITY,1.100101e+10
78159,3FA6P0PU8F,Kern,Ridgecrest,CA,93555.0,2015,FORD,FUSION,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,19,0,NaN,475775205,POINT (-117.67228 35.62073),NON WASHINGTON STATE ELECTRIC UTILITY,6.029005e+09
79645,5UXKT0C36H,Cumberland,Fayetteville,NC,28305.0,2017,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,14,0,NaN,110287313,POINT (-78.90195 35.058245),NON WASHINGTON STATE ELECTRIC UTILITY,3.705100e+10
79711,2C4RC1H78J,Oldham,Goshen,KY,40026.0,2018,CHRYSLER,PACIFICA,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,33,0,NaN,277234681,POINT (-85.5824778 38.4053653),NON WASHINGTON STATE ELECTRIC UTILITY,2.118503e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177492,5YJ3E1EB4J,Jefferson,Watertown,NY,13603.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,0,NaN,151504335,POINT (-75.8131886 44.045225),NON WASHINGTON STATE ELECTRIC UTILITY,3.604506e+10
177532,7SAXCBE62N,Loudoun,Aldie,VA,20105.0,2022,TESLA,MODEL X,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,NaN,198763512,POINT (-77.55783 38.9221),NON WASHINGTON STATE ELECTRIC UTILITY,5.110761e+10
177682,5YJ3E1EC2P,Frederick,Frederick,MD,21701.0,2023,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,NaN,244377416,POINT (-77.409075 39.416495),NON WASHINGTON STATE ELECTRIC UTILITY,2.402175e+10
177785,JTMEB3FV8P,Frederick,Middletown,MD,21769.0,2023,TOYOTA,RAV4 PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,42,0,NaN,251425919,POINT (-77.54559 39.44235),NON WASHINGTON STATE ELECTRIC UTILITY,2.402175e+10
177843,3FMTK3RM7M,Hardin,Elizabethtown,KY,42701.0,2021,FORD,MUSTANG MACH-E,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,NaN,212029016,POINT (-85.85707 37.69646),NON WASHINGTON STATE ELECTRIC UTILITY,2.109300e+10

In [27]:
ev_df.duplicated().sum()

0

In [28]:
ev_df['Electric Vehicle Type'].unique()

array(['Battery Electric Vehicle (BEV)',
       'Plug-in Hybrid Electric Vehicle (PHEV)'], dtype=object)

In [29]:
ev_df['Electric Vehicle Type'].value_counts()

Electric Vehicle Type
Battery Electric Vehicle (BEV)            139210
Plug-in Hybrid Electric Vehicle (PHEV)     38656
Name: count, dtype: int64

In [32]:
ev_df['Legislative District'].value_counts()

Legislative District
41.0    11553
45.0    10737
48.0     9817
1.0      7786
5.0      7614
11.0     7507
36.0     7389
46.0     6901
43.0     6524
37.0     5215
34.0     5155
18.0     4744
44.0     4677
21.0     4410
22.0     4399
32.0     4358
23.0     3830
40.0     3798
33.0     3550
26.0     3538
47.0     3230
31.0     3100
10.0     3018
17.0     3000
39.0     2593
27.0     2522
35.0     2488
42.0     2444
24.0     2391
49.0     2390
28.0     2277
30.0     2120
2.0      2015
25.0     1838
8.0      1831
38.0     1736
6.0      1691
12.0     1644
20.0     1582
4.0      1470
13.0     1211
29.0     1183
14.0     1123
19.0     1032
9.0      1003
16.0      885
3.0       876
7.0       839
15.0      443
Name: count, dtype: int64

In [41]:
ev_df1 = ev_df[~ev_df['City'].isnull()]

In [43]:
ev_df1.isnull().sum()

VIN (1-10)                                             0
County                                                 0
City                                                   0
State                                                  0
Postal Code                                            0
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         0
Base MSRP                                              0
Legislative District                                 384
DOL Vehicle ID                                         0
Vehicle Location                                       4
Electric Utility                                       0
2020 Census Tract                                      0
dtype: int64

In [45]:
ev_df1['Base MSRP'].unique()

array([     0,  32250,  31950,  69900,  44100,  45600,  39995,  54950,
        53400,  34995,  55700,  52900,  64950, 102000,  33950,  59900,
        36900,  52650,  91250,  98950, 110950,  36800,  90700, 184400,
        81100,  43700, 109000,  89100,  75095, 845000,  32995],
      dtype=int64)

In [52]:
ev_df1[ev_df1['Base MSRP']!=0].count()

VIN (1-10)                                           3343
County                                               3343
City                                                 3343
State                                                3343
Postal Code                                          3343
Model Year                                           3343
Make                                                 3343
Model                                                3343
Electric Vehicle Type                                3343
Clean Alternative Fuel Vehicle (CAFV) Eligibility    3343
Electric Range                                       3343
Base MSRP                                            3343
Legislative District                                 3331
DOL Vehicle ID                                       3343
Vehicle Location                                     3343
Electric Utility                                     3343
2020 Census Tract                                    3343
dtype: int64

In [55]:
#Which brand cars are most sold?
ev_df1['Make'].value_counts()

Make
TESLA                   79655
NISSAN                  13997
CHEVROLET               13678
FORD                     9199
BMW                      7570
KIA                      7432
TOYOTA                   6288
VOLKSWAGEN               5004
JEEP                     4480
HYUNDAI                  4406
RIVIAN                   4312
VOLVO                    4133
AUDI                     3646
CHRYSLER                 2993
MERCEDES-BENZ            1589
PORSCHE                  1139
MITSUBISHI                958
MINI                      898
POLESTAR                  882
HONDA                     833
SUBARU                    831
FIAT                      784
DODGE                     568
MAZDA                     476
CADILLAC                  382
LEXUS                     370
SMART                     270
LINCOLN                   267
LUCID                     240
JAGUAR                    232
GENESIS                   182
LAND ROVER                 56
FISKER                     49
ALFA ROMEO                 39
AZURE DYNAMICS              8
TH!NK                       5
GMC                         3
BENTLEY                     3
WHEEGO ELECTRIC CARS        3
ROLLS ROYCE                 1
Name: count, dtype: int64

In [62]:
#Which model number EVs are most sold?
ev_df1['Make & Model'] = ev_df1['Make']+ ' ' + ev_df1['Model']
ev_df1['Make & Model']

C:\Users\srired\AppData\Local\Temp\ipykernel_1484\445072980.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ev_df1['Make & Model'] = ev_df1['Make']+ ' ' + ev_df1['Model']

0                 TESLA MODEL Y
1                 TESLA MODEL Y
2                 TESLA MODEL S
3                 TESLA MODEL S
4                 TESLA MODEL Y
                  ...
177861            TESLA MODEL Y
177862    HYUNDAI KONA ELECTRIC
177863            TESLA MODEL Y
177864          VOLKSWAGEN ID.4
177865            TESLA MODEL 3
Name: Make & Model, Length: 177861, dtype: object

In [63]:
ev_df1['Make & Model'].value_counts()

Make & Model
TESLA MODEL Y            35989
TESLA MODEL 3            30091
NISSAN LEAF              13365
TESLA MODEL S             7734
CHEVROLET BOLT EV         6821
                         ...
BMW 745LE                    2
PORSCHE 918                  1
CHEVROLET S-10 PICKUP        1
ROLLS ROYCE SPECTRE          1
BENTLEY BENTAYGA             1
Name: count, Length: 139, dtype: int64

In [66]:
ev_df1['Base MSRP'].unique()

array([     0,  32250,  31950,  69900,  44100,  45600,  39995,  54950,
        53400,  34995,  55700,  52900,  64950, 102000,  33950,  59900,
        36900,  52650,  91250,  98950, 110950,  36800,  90700, 184400,
        81100,  43700, 109000,  89100,  75095, 845000,  32995],
      dtype=int64)

In [67]:
ev_df1['Base MSRP'].value_counts()

Base MSRP
0         174518
69900       1370
31950        381
52900        222
32250        136
59900        128
54950        126
39995        113
36900        104
44100         92
45600         82
64950         81
33950         76
52650         68
34995         66
36800         55
55700         54
53400         37
81100         23
110950        20
98950         19
90700         19
75095         14
102000        13
184400        10
43700         10
89100          8
109000         7
91250          5
32995          3
845000         1
Name: count, dtype: int64

In [69]:
#create a function to define the prices in ranges
def create_price_range(df, column='Base MSRP'):
    def categorize_price(price):
        if price == 0:
            return "Unknown"
        elif price < 40000:
            return "Low"
        elif price < 60000:
            return "Medium"
        else:
            return "High"
    df["Price_Range_Category"] = df[column].apply(categorize_price)
    return df
ev_df2 = create_price_range(ev_df1,column="Base MSRP")

C:\Users\srired\AppData\Local\Temp\ipykernel_1484\438329052.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price_Range_Category"] = df[column].apply(categorize_price)

In [70]:
ev_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 177861 entries, 0 to 177865
Data columns (total 19 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         177861 non-null  object
 1   County                                             177861 non-null  object
 2   City                                               177861 non-null  object
 3   State                                              177861 non-null  object
 4   Postal Code                                        177861 non-null  float64
 5   Model Year                                         177861 non-null  int64
 6   Make                                               177861 non-null  object
 7   Model                                              177861 non-null  object
 8   Electric Vehicle Type                              177861 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  177861 non-null  object
 10  Electric Range                                     177861 non-null  int64
 11  Base MSRP                                          177861 non-null  int64
 12  Legislative District                               177477 non-null  float64
 13  DOL Vehicle ID                                     177861 non-null  int64
 14  Vehicle Location                                   177857 non-null  object
 15  Electric Utility                                   177861 non-null  object
 16  2020 Census Tract                                  177861 non-null  float64
 17  Make & Model                                       177861 non-null  object
 18  Price_Range_Category                               177861 non-null  object
dtypes: float64(3), int64(4), object(12)
memory usage: 27.1+ MB

In [71]:
ev_df2['Electric Range'].value_counts()

Electric Range
0      91950
215     6376
220     4113
25      4107
32      3911
       ...
36         4
95         3
11         3
51         3
57         2
Name: count, Length: 102, dtype: int64

In [74]:
#create a distance ranges using numpy
def create_electric_range(df,column="Electric Range"):
    conditions = [df[column]==0, df[column]<150, df[column]<300]
    categories =["Unknown", "Short", "Medium"]
    df["Electric_Range_Category"] = np.select(conditions, categories, default = "Long")
    return df
ev_df3 = create_electric_range(ev_df2,column="Electric Range")

C:\Users\srired\AppData\Local\Temp\ipykernel_1484\3376648747.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Electric_Range_Category"] = np.select(conditions, categories, default = "Long")

In [78]:
ev_df3["Electric_Range_Category"].value_counts()

Electric_Range_Category
Unknown    91950
Short      50654
Medium     32653
Long        2604
Name: count, dtype: int64

In [80]:
ev_df3['State'].value_counts()

State
WA    177477
CA       101
VA        46
MD        31
TX        23
NC        16
IL        15
CO        12
AZ        10
FL        10
HI         9
NV         8
NJ         8
SC         7
NY         7
CT         6
GA         6
AL         6
MA         5
MO         5
OR         5
OH         4
PA         4
LA         4
ID         3
UT         3
IN         3
KY         3
DC         3
RI         2
MI         2
WY         2
NE         2
MN         2
AR         2
KS         2
IA         1
TN         1
NH         1
AK         1
OK         1
DE         1
NM         1
Name: count, dtype: int64